<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Week 4 In-class Assignment">
<meta name="dcterms.date" content="2024-09-30">

<title>CHL8010: Statistical Programming and Computation in Health Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="week4_eda_inclass_files/libs/clipboard/clipboard.min.js"></script>
<script src="week4_eda_inclass_files/libs/quarto-html/quarto.js"></script>
<script src="week4_eda_inclass_files/libs/quarto-html/popper.min.js"></script>
<script src="week4_eda_inclass_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="week4_eda_inclass_files/libs/quarto-html/anchor.min.js"></script>
<link href="week4_eda_inclass_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="week4_eda_inclass_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="week4_eda_inclass_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="week4_eda_inclass_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="week4_eda_inclass_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CHL8010: Statistical Programming and Computation in Health Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Week 4 In-class Assignment </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Observations from Canada should look like this…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Final_data <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(country_name <span class="sc">==</span> <span class="st">"Canada"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   country_name ISO           region  gdp1000 OECD OECD2023  popdens    urban
1        Canada CAN Northern America 24.27100    1        1 66.19704 56.14335
2        Canada CAN Northern America 23.82206    1        1 66.45361 56.40270
3        Canada CAN Northern America 24.25534    1        1 66.71112 56.67093
4        Canada CAN Northern America 28.30046    1        1 66.96384 56.94365
5        Canada CAN Northern America 32.14368    1        1 67.21715 57.20020
6        Canada CAN Northern America 36.38251    1        1 67.47283 57.41671
7        Canada CAN Northern America 40.50406    1        1 67.73674 57.59143
8        Canada CAN Northern America 44.65990    1        1 67.99444 57.75691
9        Canada CAN Northern America 46.71051    1        1 68.25765 57.97905
10       Canada CAN Northern America 40.87631    1        1 68.53354 58.24228
11       Canada CAN Northern America 47.56208    1        1 68.80739 58.52809
12       Canada CAN Northern America 52.22370    1        1 69.04842 58.81437
13       Canada CAN Northern America 52.66909    1        1 69.27604 59.05573
14       Canada CAN Northern America 52.63517    1        1 69.50772 59.19713
15       Canada CAN Northern America 50.95600    1        1 69.76876 59.30361
16       Canada CAN Northern America 43.59614    1        1 69.98853 59.42627
17       Canada CAN Northern America 42.31560    1        1 70.21484 59.50521
18       Canada CAN Northern America 45.12943    1        1 70.40863 59.59325
19       Canada CAN Northern America 46.54864    1        1 70.63614 59.68433
20       Canada CAN Northern America 46.32867    1        1 70.83794 59.75984
     agedep male_edu     temp rainfall1000 Year Totdeath Conflict MatMor NeoMor
1  46.34463 12.30281 5.486244    0.9971559 2000       11        0      9    3.8
2  45.89632 12.35258 6.469105    0.8644873 2001       23        0     10    3.8
3  45.46660 12.40182 5.979147    0.9460938 2002        1        0     10    3.9
4  45.07468 12.45053 5.416964    1.0189234 2003        0        0     10    3.9
5  44.67374 12.49870 5.556961    1.0008237 2004        0        0     10    3.9
6  44.26641 12.54635 6.187472    1.0367199 2005        0        0     11    3.9
7  43.96370 12.59349 6.895084    1.0917386 2006        0        0     11    3.9
8  43.83612 12.64015 5.900051    1.0134091 2007        0        0     11    3.8
9  43.85426 12.68634 5.650118    1.0693435 2008        0        0     12    3.8
10 43.94937 12.73207 5.398867    0.9928497 2009        0        0     12    3.8
11 44.13587 12.77735 6.781766    1.0379754 2010        0        0     11    3.8
12 44.53578 12.82218 6.269133    1.1343442 2011        0        0     11    3.7
13 45.18393 12.86660 7.249497    0.9747708 2012        0        0     11    3.7
14 45.95404 12.91059 5.954381    1.0282075 2013        0        0     11    3.6
15 46.75493 12.95414 5.584650    1.0377695 2014        0        0     11    3.6
16 47.59164 12.99723 6.436884    0.9632446 2015        0        0     11    3.6
17 48.41410 13.03988 7.184514    0.9677826 2016        0        0     10    3.5
18 49.14806 13.08210 6.539669    1.0995322 2017        0        0     10    3.4
19 49.80166 13.12388 6.539677    1.0991469 2018        0        0     NA    3.3
20 50.47739 13.16522 6.539633    1.0987523 2019        0        0     NA    3.3
   InfMor Und5Mor drought earthquake
1     5.3     6.2       0          0
2     5.3     6.2       0          0
3     5.3     6.2       0          0
4     5.3     6.2       0          0
5     5.3     6.1       0          0
6     5.2     6.1       0          0
7     5.2     6.0       0          0
8     5.1     6.0       0          0
9     5.1     5.9       0          0
10    5.0     5.8       0          0
11    5.0     5.7       0          0
12    4.9     5.7       0          0
13    4.9     5.6       0          0
14    4.8     5.5       0          0
15    4.7     5.4       0          0
16    4.7     5.4       0          0
17    4.6     5.3       0          0
18    4.6     5.2       0          0
19    4.5     5.1       0          0
20    4.4     5.1       0          0</code></pre>
</div>
</div>
<p>Observations from Ecuador should look like this…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Final_data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(country_name <span class="sc">==</span> <span class="st">"Ecuador"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   country_name ISO                          region  gdp1000 OECD OECD2023
1       Ecuador ECU Latin America and the Caribbean 1.451531    0        0
2       Ecuador ECU Latin America and the Caribbean 1.904814    0        0
3       Ecuador ECU Latin America and the Caribbean 2.184209    0        0
4       Ecuador ECU Latin America and the Caribbean 2.438344    0        0
5       Ecuador ECU Latin America and the Caribbean 2.703566    0        0
6       Ecuador ECU Latin America and the Caribbean 3.014310    0        0
7       Ecuador ECU Latin America and the Caribbean 3.340841    0        0
8       Ecuador ECU Latin America and the Caribbean 3.579032    0        0
9       Ecuador ECU Latin America and the Caribbean 4.260433    0        0
10      Ecuador ECU Latin America and the Caribbean 4.240703    0        0
11      Ecuador ECU Latin America and the Caribbean 4.640246    0        0
12      Ecuador ECU Latin America and the Caribbean 5.202656    0        0
13      Ecuador ECU Latin America and the Caribbean 5.678456    0        0
14      Ecuador ECU Latin America and the Caribbean 6.050355    0        0
15      Ecuador ECU Latin America and the Caribbean 6.374631    0        0
16      Ecuador ECU Latin America and the Caribbean 6.130587    0        0
17      Ecuador ECU Latin America and the Caribbean 6.079089    0        0
18      Ecuador ECU Latin America and the Caribbean 6.246404    0        0
19      Ecuador ECU Latin America and the Caribbean 6.321349    0        0
20      Ecuador ECU Latin America and the Caribbean 6.233258    0        0
    popdens    urban   agedep male_edu     temp rainfall1000 Year Totdeath
1  23.27432 36.19963 67.44216 7.738627 19.54855    1.4201653 2000        0
2  23.39372 36.67994 66.57356 7.843942 19.66622    1.1667746 2001        0
3  23.52087 37.08903 65.65488 7.949449 20.24695    1.4577981 2002        2
4  23.58358 37.23792 64.71472 8.055240 20.05016    1.5781807 2003        0
5  38.43743 37.39268 63.78049 8.161433 20.10136    1.0683450 2004       26
6  38.55361 37.36968 62.86530 8.268176 19.88163    0.8555447 2005        0
7  38.65018 37.47567 61.97042 8.375587 20.07087    1.1114502 2006        0
8  38.76505 37.68172 61.11422 8.483729 19.49536    1.0899082 2007        0
9  38.83977 37.67445 60.31015 8.592603 19.85711    1.6184816 2008        0
10 38.92613 37.39437 59.55262 8.702180 20.39298    1.0870796 2009       25
11 39.03066 37.26838 58.83793 8.812409 20.11160    1.7045703 2010        0
12 39.09586 37.61553 58.16553 8.923172 19.86633    1.4518388 2011        0
13 39.13343 38.00733 57.51051 9.034284 20.19000    1.7520003 2012        0
14 39.18619 38.22511 56.84804 9.145523 19.85177    1.3735605 2013        0
15 39.27871 38.12421 56.17001 9.256679 20.42252    1.2572257 2014        0
16 39.38824 38.15633 55.46511 9.367582 20.95595    1.7284273 2015        0
17 39.46201 38.45745 54.73369 9.478071 20.77476    1.3168761 2016        0
18 39.53609 38.65993 53.99096 9.587993 20.53262    1.9544485 2017        0
19 39.58380 38.87253 53.12249 9.697221 20.53714    1.9573265 2018        0
20 39.75109 39.05144 52.29278 9.805670 20.54169    1.9602443 2019        0
   Conflict MatMor NeoMor InfMor Und5Mor drought earthquake
1         0    122   14.1   24.7    29.5       0          0
2         0    117   13.4   23.4    28.0       0          0
3         0    110   12.7   22.4    26.6       0          0
4         0    100   12.1   21.5    25.4       0          0
5         1     94   11.6   20.7    24.4       0          0
6         0     94   11.1   19.9    23.5       0          0
7         0     90   10.6   19.2    22.6       0          0
8         0     85   10.2   18.5    21.7       0          0
9         0     82    9.7   17.7    20.8       0          0
10        1     80    9.3   17.0    19.9       1          0
11        0     78    8.9   16.3    19.0       0          0
12        0     76    8.5   15.6    18.1       0          0
13        0     71    8.1   14.9    17.3       0          0
14        0     67    7.8   14.3    16.6       1          0
15        0     65    7.5   13.7    15.9       0          1
16        0     63    7.3   13.2    15.4       0          0
17        0     61    7.1   12.8    14.8       0          2
18        0     59    6.9   12.4    14.4       0          0
19        0     NA    6.9   12.0    13.9       0          0
20        0     NA    6.8   11.6    13.4       0          2</code></pre>
</div>
</div>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<p>Use the rest of the class time to explore the final data that will be used for analysis starting next week. At the end of the class, write a summary of your findings and push your <strong>Quarto document (pdf)</strong> to your repo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Final_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  country_name ISO        region   gdp1000 OECD OECD2023  popdens    urban
1  Afghanistan AFG Southern Asia        NA    0        0 14.13654 16.25324
2  Afghanistan AFG Southern Asia        NA    0        0 14.23156 16.25661
3  Afghanistan AFG Southern Asia 0.1835328    0        0 14.32270 16.42654
4  Afghanistan AFG Southern Asia 0.2004626    0        0 14.40691 16.60701
5  Afghanistan AFG Southern Asia 0.2216576    0        0 15.21947 16.71367
6  Afghanistan AFG Southern Asia 0.2550551    0        0 15.33619 16.85096
    agedep male_edu     temp rainfall1000 Year Totdeath Conflict MatMor NeoMor
1 108.3466 2.762086 12.69959    0.2763704 2000     5065        1   1450   60.9
2 108.9899 2.856936 12.85570    0.2793079 2001     5394        1   1390   59.7
3 109.3472 2.954241 12.71081    0.3805710 2002     5553        1   1300   58.5
4 109.4475 3.054121 12.16592    0.4288939 2003     1157        1   1240   57.2
5 109.2868 3.156706 13.04643    0.3754336 2004      944        1   1180   55.9
6 107.9646 3.262133 12.23141    0.4415680 2005      817        1   1140   54.6
  InfMor Und5Mor drought earthquake
1   90.5   129.2       1          0
2   87.9   125.2       0          2
3   85.3   121.1       0          3
4   82.7   116.9       0          1
5   80.0   112.6       0          1
6   77.3   108.4       0          2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(Final_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     country_name ISO             region  gdp1000 OECD OECD2023  popdens
3715     Zimbabwe ZWE Sub-Saharan Africa 1.407034    0        0 26.52884
3716     Zimbabwe ZWE Sub-Saharan Africa 1.410329    0        0 26.54454
3717     Zimbabwe ZWE Sub-Saharan Africa 1.421788    0        0 26.53811
3718     Zimbabwe ZWE Sub-Saharan Africa 1.192107    0        0 26.49281
3719     Zimbabwe ZWE Sub-Saharan Africa 2.269177    0        0 26.47943
3720     Zimbabwe ZWE Sub-Saharan Africa 1.421869    0        0 26.46341
        urban   agedep male_edu     temp rainfall1000 Year Totdeath Conflict
3715 24.40427 85.87550 8.679591 20.87651    0.6777257 2014        0        0
3716 24.75233 85.08337 8.785078 21.45470    0.4490721 2015        0        0
3717 25.02842 84.11222 8.889947 21.39290    0.4939246 2016        0        0
3718 25.29333 83.10129 8.994252 20.85962    0.9533149 2017        0        0
3719 25.53759 82.12335 9.098048 20.86041    0.9535655 2018        0        0
3720 25.70572 81.20786 9.201384 20.86120    0.9538138 2019        4        0
     MatMor NeoMor InfMor Und5Mor drought earthquake
3715    494   28.2   42.9    62.7       0          0
3716    480   27.8   42.1    61.3       0          0
3717    468   27.4   40.8    58.7       0          0
3718    458   27.0   39.9    57.0       1          0
3719     NA   26.6   38.8    54.8       0          0
3720     NA   26.2   38.1    54.2       0          0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Final_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3720   21</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Final_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   3720 obs. of  21 variables:
 $ country_name: chr  "Afghanistan" "Afghanistan" "Afghanistan" "Afghanistan" ...
 $ ISO         : chr  "AFG" "AFG" "AFG" "AFG" ...
 $ region      : chr  "Southern Asia" "Southern Asia" "Southern Asia" "Southern Asia" ...
 $ gdp1000     : num  NA NA 0.184 0.2 0.222 ...
 $ OECD        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ OECD2023    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ popdens     : num  14.1 14.2 14.3 14.4 15.2 ...
 $ urban       : num  16.3 16.3 16.4 16.6 16.7 ...
 $ agedep      : num  108 109 109 109 109 ...
 $ male_edu    : num  2.76 2.86 2.95 3.05 3.16 ...
 $ temp        : num  12.7 12.9 12.7 12.2 13 ...
 $ rainfall1000: num  0.276 0.279 0.381 0.429 0.375 ...
 $ Year        : int  2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 ...
 $ Totdeath    : int  5065 5394 5553 1157 944 817 1711 4982 7020 5660 ...
 $ Conflict    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ MatMor      : int  1450 1390 1300 1240 1180 1140 1120 1090 1030 993 ...
 $ NeoMor      : num  60.9 59.7 58.5 57.2 55.9 54.6 53.2 51.7 50.3 48.9 ...
 $ InfMor      : num  90.5 87.9 85.3 82.7 80 77.3 74.6 71.9 69.2 66.7 ...
 $ Und5Mor     : num  129 125 121 117 113 ...
 $ drought     : int  1 0 0 0 0 0 1 0 1 0 ...
 $ earthquake  : int  0 2 3 1 1 2 1 0 0 1 ...</code></pre>
</div>
</div>
<p>3720 rows by 21 columns Data types include: 3 character, 8 integer, and 10 numerical</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data shows 186 countries each with 20 rows</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Final_data <span class="sc">%&gt;%</span> <span class="fu">count</span>(ISO)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ISO  n
1   AFG 20
2   AGO 20
3   ALB 20
4   AND 20
5   ARE 20
6   ARG 20
7   ARM 20
8   ATG 20
9   AUS 20
10  AUT 20
11  AZE 20
12  BDI 20
13  BEL 20
14  BEN 20
15  BFA 20
16  BGD 20
17  BGR 20
18  BHR 20
19  BHS 20
20  BIH 20
21  BLR 20
22  BLZ 20
23  BOL 20
24  BRA 20
25  BRB 20
26  BRN 20
27  BTN 20
28  BWA 20
29  CAF 20
30  CAN 20
31  CHE 20
32  CHL 20
33  CHN 20
34  CIV 20
35  CMR 20
36  COD 20
37  COG 20
38  COL 20
39  COM 20
40  CPV 20
41  CRI 20
42  CUB 20
43  CYP 20
44  CZE 20
45  DEU 20
46  DJI 20
47  DMA 20
48  DNK 20
49  DOM 20
50  DZA 20
51  ECU 20
52  EGY 20
53  ERI 20
54  ESP 20
55  EST 20
56  ETH 20
57  FIN 20
58  FJI 20
59  FRA 20
60  FSM 20
61  GAB 20
62  GBR 20
63  GEO 20
64  GHA 20
65  GIN 20
66  GMB 20
67  GNB 20
68  GNQ 20
69  GRC 20
70  GRD 20
71  GTM 20
72  GUY 20
73  HND 20
74  HRV 20
75  HTI 20
76  HUN 20
77  IDN 20
78  IND 20
79  IRL 20
80  IRN 20
81  IRQ 20
82  ISL 20
83  ITA 20
84  JAM 20
85  JOR 20
86  JPN 20
87  KAZ 20
88  KEN 20
89  KGZ 20
90  KHM 20
91  KIR 20
92  KOR 20
93  KWT 20
94  LAO 20
95  LBN 20
96  LBR 20
97  LBY 20
98  LCA 20
99  LKA 20
100 LSO 20
101 LTU 20
102 LUX 20
103 LVA 20
104 MAR 20
105 MDA 20
106 MDG 20
107 MDV 20
108 MEX 20
109 MHL 20
110 MKD 20
111 MLI 20
112 MLT 20
113 MMR 20
114 MNE 20
115 MNG 20
116 MOZ 20
117 MRT 20
118 MUS 20
119 MWI 20
120 MYS 20
121 NAM 20
122 NER 20
123 NGA 20
124 NIC 20
125 NLD 20
126 NOR 20
127 NPL 20
128 NZL 20
129 OMN 20
130 PAK 20
131 PAN 20
132 PER 20
133 PHL 20
134 PNG 20
135 POL 20
136 PRI 20
137 PRK 20
138 PRT 20
139 PRY 20
140 QAT 20
141 ROU 20
142 RUS 20
143 RWA 20
144 SAU 20
145 SDN 20
146 SEN 20
147 SGP 20
148 SLB 20
149 SLE 20
150 SLV 20
151 SOM 20
152 SRB 20
153 SSD 20
154 STP 20
155 SUR 20
156 SVK 20
157 SVN 20
158 SWE 20
159 SWZ 20
160 SYC 20
161 SYR 20
162 TCD 20
163 TGO 20
164 THA 20
165 TJK 20
166 TKM 20
167 TLS 20
168 TON 20
169 TTO 20
170 TUN 20
171 TUR 20
172 TZA 20
173 UGA 20
174 UKR 20
175 URY 20
176 USA 20
177 UZB 20
178 VCT 20
179 VEN 20
180 VNM 20
181 VUT 20
182 WSM 20
183 YEM 20
184 ZAF 20
185 ZMB 20
186 ZWE 20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Final_data <span class="sc">%&gt;%</span> <span class="fu">count</span>(ISO) <span class="sc">%&gt;%</span> <span class="fu">count</span>(n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   n  nn
1 20 186</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting conflicts by ISO Code (only for countries with minimum 1 conflict)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>conflict_data <span class="ot">&lt;-</span> Final_data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ISO) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_conflicts =</span> <span class="fu">sum</span>(Conflict, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_conflicts <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_conflicts))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>conflict_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 88 × 2
   ISO   total_conflicts
   &lt;chr&gt;           &lt;int&gt;
 1 AFG                20
 2 COD                20
 3 COL                20
 4 DZA                20
 5 ETH                20
 6 IND                20
 7 IRQ                20
 8 MMR                20
 9 NGA                20
10 PAK                20
# ℹ 78 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting deaths by ISO Code (only for countries with minimum 1 conflict related death)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>death_data <span class="ot">&lt;-</span> Final_data <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ISO) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_deaths =</span> <span class="fu">sum</span>(Totdeath, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_deaths <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_deaths))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>death_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 2
   ISO   total_deaths
   &lt;chr&gt;        &lt;int&gt;
 1 SYR         386891
 2 AFG         171391
 3 IRQ          91429
 4 ETH          87066
 5 COD          52492
 6 SDN          51355
 7 NGA          51114
 8 PAK          40789
 9 IND          32704
10 MEX          32686
# ℹ 90 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot for conflict</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(conflict_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ISO, <span class="sc">-</span>total_conflicts), <span class="at">y =</span> total_conflicts)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Conflict Count by ISO Code"</span>, <span class="at">x =</span> <span class="st">"ISO Code"</span>, <span class="at">y =</span> <span class="st">"Conflict Count"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)  </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="week4_eda_inclass_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(death_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ISO, <span class="sc">-</span>total_deaths), <span class="at">y =</span> total_deaths)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Conflict Death Count by ISO Code"</span>, <span class="at">x =</span> <span class="st">"ISO Code"</span>, <span class="at">y =</span> <span class="st">"Conflict Death Count"</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="week4_eda_inclass_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>conflict_summary <span class="ot">&lt;-</span> Final_data <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Conflict) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Totdeath, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(conflict_summary, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean, <span class="at">color =</span> <span class="fu">as.factor</span>(Conflict), <span class="at">group =</span> Conflict)) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Conflict Related Deaths by Year Grouped by Conflict Status"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Deaths"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Conflict Status"</span>) <span class="sc">+</span>  </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"blue"</span>))  <span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="week4_eda_inclass_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Analyze missingness</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>missingness <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Final_data))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>missingness</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 648</code></pre>
</div>
</div>
<p>648 total missing values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>missingness_column <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(Final_data))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>missingness_column</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>country_name          ISO       region      gdp1000         OECD     OECD2023 
           0            0            0           62            0            0 
     popdens        urban       agedep     male_edu         temp rainfall1000 
          20           20            0           20           20           20 
        Year     Totdeath     Conflict       MatMor       NeoMor       InfMor 
           0            0            0          426           20           20 
     Und5Mor      drought   earthquake 
          20            0            0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>missing_percent <span class="ot">&lt;-</span> <span class="fu">round</span>(missingness_column<span class="sc">/</span> <span class="fu">nrow</span>(Final_data) <span class="sc">*</span> <span class="dv">100</span>,<span class="dv">3</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>missing_percent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>country_name          ISO       region      gdp1000         OECD     OECD2023 
       0.000        0.000        0.000        1.667        0.000        0.000 
     popdens        urban       agedep     male_edu         temp rainfall1000 
       0.538        0.538        0.000        0.538        0.538        0.538 
        Year     Totdeath     Conflict       MatMor       NeoMor       InfMor 
       0.000        0.000        0.000       11.452        0.538        0.538 
     Und5Mor      drought   earthquake 
       0.538        0.000        0.000 </code></pre>
</div>
</div>
<p>Maternal mortality had the most missingness of the outcome variables (N = 426 or 11.45%)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation of Outcome variables</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(Final_data[, <span class="fu">c</span>(<span class="st">"MatMor"</span>, <span class="st">"NeoMor"</span>, <span class="st">"InfMor"</span>, <span class="st">"Und5Mor"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        MatMor NeoMor InfMor Und5Mor
MatMor  1.0000 0.8355 0.8786  0.8995
NeoMor  0.8355 1.0000 0.9591  0.9279
InfMor  0.8786 0.9591 1.0000  0.9861
Und5Mor 0.8995 0.9279 0.9861  1.0000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Longitudinal Maternal Mortality trends by ISO Code</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Final_data, <span class="fu">aes</span>(Year, MatMor)) <span class="sc">+</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> ISO), <span class="at">alpha =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Maternal Mortality trends by ISO Code"</span>, <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Maternal Mortality"</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span> </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 426 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 426 rows containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="week4_eda_inclass_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>