---
title: "Simulation"
author: "Alex G"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
library(foreach)
library(knitr)
library(parallel)
library(tictoc)  # for timing comparisons
library(dplyr)
```

```{r}
## set simulation parameters
n <- 100     # sample size
pz <- 0.2    # probability of Z = 1
alpha0 <- 0  # logit probability of x = 1 in non-smokers (z = 0)    
alpha1 <- 1  # log odds ratio of x = 1 in smokers (z = 1) vs non-smokers
beta0 <- -3  # logit prob of y = 1 in non-coffee drinkers (x = 0) and non-smokers (z = 0)
beta1 <- 0       
beta2 <- 2

## generate confounder Z from a binomial distribution
z <- rbinom(n, size = 1, prob = pz)
## compute probability of observing X = 1 from the inverse logit function
px <- exp(alpha0 + alpha1 * z) / (1 + exp(alpha0 + alpha1 * z))
## randomly generate binary variable X from the above probability
x <- rbinom(n, size = 1, prob = px)
## randomly generate binary variable Y from the inverse logistic function
py <- exp(beta0 + beta1 * x + beta2 * z) / (1 + exp(beta0 + beta1 * x + beta2 * z))
y <- rbinom(n, size = 1, prob = py)
```


```{r}
```


```{r}
```


```{r}
```

